import type { Metadata } from "next";
import "./globals.css";
import "@xionwcfm/token/style";
import "@xionwcfm/xds/style";

import { Toaster } from "@xionwcfm/xds/toast";
import { Providers } from "~/src/providers";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Toaster closeButton duration={1500} expand />
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
